# Generated by Django 4.2.5 on 2023-09-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_category_level_category_lft_category_rght_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tree_id',
        ),
    ]
